@echo off
echo Starting AI News Debate Platform...

echo Starting backend server...
start cmd /k "cd backend && npm run dev"

echo Starting frontend application...
timeout /t 5
start cmd /k "npm start"

echo Both servers are starting. Please wait a moment...
echo Frontend will be available at http://localhost:3000 (or another port if 3000 is in use)
